let a = [12,67,10,98,69];
document.write(a);
document.write("<br>");
let  totalitems= a.length;
document.write("total items = "+totalitems); 
document.write("<br>");
document.write(a[2]);
document.write("<br>");
document.write(a[1]);
document.write("<br>");